buildscript {
    repositories {
        mavenCentral()
        maven { url 'https://cdn.fox2code.com/maven' }
    }
    dependencies {
        classpath('com.fox2code.FoxLoader:dev:2.0-alpha32')
    }
}

apply plugin: 'foxloader.dev'

group = 'net.tracystacktrace'
version = '1.0.2'

configurations {
    implAndInclude
    implAndInclude.transitive = false
    implementation.extendsFrom(implAndInclude)
}

dependencies {
    api 'org.semver4j:semver4j:5.3.0'
    testImplementation platform('org.junit:junit-bom:5.10.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'

    implAndInclude('com.h2database:h2:2.2.220')
}

test {
    useJUnitPlatform()
}

jar {
    from(provider {
        configurations.implAndInclude.collect {
            it.isDirectory() ? it : zipTree(it)
        }
    }) {
        exclude 'META-INF/MANIFEST.MF'
        exclude 'META-INF/*.SF'
        exclude 'META-INF/*.DSA'
        exclude 'META-INF/*.RSA'
        exclude '**/package-info.class'
        exclude '**/module-info.class'
        exclude 'assets/*/icon.png'
    }
    from "LICENSE"
}

foxloader {
    modId = "authon"
    modName = "AuthOn"
    modVersion = project.version
    modWebsite = "https://codeberg.org/tracystacktrace/authon"
    modAuthors = "tracystacktrace"
    modMain = "net.tracystacktrace.authon.AuthonServer"
    modDesc("A simple auth mod for FoxLoader servers")
}